# =============================================================================
# pcap-analyzer — dns_anomaly.py
# GitHub Repo : github.com/HunterBFranklin/pcap-analyzer
# Created     : Aug. 7, 2026
# Modified    : Sep. 10, 2026
# =============================================================================

from scapy.all import *
from math import log2
from collections import Counter
from datetime import datetime, timezone

COMMON_SUBDOMAIN_PREFIXES = {
    "www", "mail", "login", "cdn", "api", "ftp", "smtp", "ns", "ns1", "ns2",
    "mx", "web", "dev", "staging", "prod", "static", "assets", "img", "images",
    "auth", "secure", "portal", "vpn", "remote", "owa", "autodiscover",
}

def extract_dns_queries(packets):

    """
    Extracts all Domain Name System (DNS) queries out of a raw packet list
    and returns them in a cleaner form. Forms a Python object, rather than having
    raw Scapy data.
    """

    queries = []

    for packet in packets:
        if packet.haslayer(DNS) and packet.haslayer(DNSQR):
            queried_domain = packet[DNSQR].qname.decode().rstrip('.')
            if packet.haslayer(IP):
                src_ip = packet[IP].src
                queries.append({
                    'src_ip': src_ip, 
                    'queried_domain': queried_domain,
                    'timestamp': float(packet.time)
                    })

    return queries


def get_tld(domain: str):

    """
    Extracts the Top Level Domain (TLD) from a domain string and returns it.
    """

    domain_split = domain.split(".")
    tld = domain_split[-1]
    return tld


def suspicious_sld(label: str) -> bool:
    """
    Checks if a domain label looks algorithmically generated based on digits, 
    length, and entropy.
    """

    if any(char.isdigit() for char in label):
        return True
    if len(label) >= 10 and shannon_entropy(label) > 3.8:
        return True
    return False


def get_entropy_target(domain: str) -> str:
    """
    Selects the specific domain label most likely to be generated by a DGA, 
    ignoring common prefixes to avoid false positives.

    Edge case found in testing:
    Scoring the SLD alone flags legitimate multi-label names such as
    login.microsoftonline.com because "microsoftonline" has high entropy.
    """

    labels = domain.lower().split(".")
    if len(labels) < 2:
        return domain

    if len(labels) == 2:
        return labels[0]

    subdomain_labels = labels[:-2]
    uncommon_labels = [
        label for label in subdomain_labels
        if label not in COMMON_SUBDOMAIN_PREFIXES
    ]
    if uncommon_labels:
        return max(uncommon_labels, key=shannon_entropy)

    sld = labels[-2]
    if suspicious_sld(sld):
        return sld

    return max(subdomain_labels, key=shannon_entropy)


def shannon_entropy(s: str):

    """
    Computes the Shannon entropy of a string in bits. Higher values indicate more
    randomness, which can be used to detect Domain Generation Algorithm (DGA)
    activity.
    """

    if s is None:
        return 0

    string_length = len(s)
    string_count = Counter(s)
    entropy = 0

    for value in string_count.values():
        p_c = value / string_length
        entropy += p_c * log2(p_c)

    return -entropy
 

def is_rare_tld(tld: str, blocklist: set):

    """
    Returns True if the Top-level Domain (TLD) is a member of a suspicious TLD
    blocklist.
    """

    return tld in blocklist


def analyze_dns(packets, tld_blocklist: set, entropy_threshold: float, ignored_domains: list = None):

    """
    Calls extract_dns_queries, scores each domain with shannon_entropy and is_rare_tld,
    and returns alert records for flagged queries. 
    """

    if ignored_domains is None:
        ignored_domains = []

    alerts = []
    raw_packets = extract_dns_queries(packets)

    for packet in raw_packets:
        domain = packet['queried_domain']

        if any(domain.endswith(suffix) for suffix in ignored_domains):
            continue

        labels = domain.lower().split(".")
        if any(label.startswith("_") for label in labels):
            continue
        if domain.lower().endswith(".local"):
            continue

        tld = get_tld(domain)
        entropy_target = get_entropy_target(domain)
        entropy = shannon_entropy(entropy_target)
        rare_tld = is_rare_tld(tld, tld_blocklist)

        if entropy > entropy_threshold or rare_tld is True:

            if entropy > entropy_threshold and rare_tld is True:
                flag_reason = "Both high entropy and rare TLD."
            elif rare_tld is True:
                flag_reason = "TLD is rare."
            elif entropy > entropy_threshold:
                flag_reason = "High shannon entropy value."

            if entropy > entropy_threshold and rare_tld is True:
                severity = "high"
            elif entropy > entropy_threshold or rare_tld is True:
                severity = "medium"

            alert_timestamp = datetime.fromtimestamp(packet['timestamp'], tz=timezone.utc).isoformat(timespec='microseconds').replace('+00:00', 'Z')

            alert = {
                    'timestamp': alert_timestamp,
                    'detection_type': "dns_anomaly",
                    'src_ip': packet['src_ip'],
                    'queried_domain': packet['queried_domain'],
                    'tld': tld,
                    'entropy_label': entropy_target,
                    'entropy': entropy,
                    'flag_reason': flag_reason,
                    'severity': severity,
                }
            alerts.append(alert)
    return alerts